export const CUSTOMER_LOGIN_REQUEST = "CUSTOMER_LOGIN_REQUEST";
export const CUSTOMER_LOGIN_SUCCESS = "CUSTOMER_LOGIN_SUCCESS";
export const CUSTOMER_LOGIN_FAIL = "CUSTOMER_LOGIN_FAIL";
export const CUSTOMER_LOGIN_RESET = "CUSTOMER_LOGIN_RESET";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";

export const CUSTOMER_LIST_REQUEST = "CUSTOMER_LIST_REQUEST";
export const CUSTOMER_LIST_SUCCESS = "CUSTOMER_LIST_SUCCESS";
export const CUSTOMER_LIST_FAIL = "CUSTOMER_LIST_FAIL";
export const CUSTOMER_LIST_RESET = "CUSTOMER_LIST_RESET";

export const CUSTOMER_CREATE_REQUEST = "CUSTOMER_CREATE_REQUEST";
export const CUSTOMER_CREATE_SUCCESS = "CUSTOMER_CREATE_SUCCESS";
export const CUSTOMER_CREATE_FAIL = "CUSTOMER_CREATE_FAIL";
export const CUSTOMER_CREATE_RESET = "CUSTOMER_CREATE_RESET";

export const CUSTOMER_SINGLE_REQUEST = "CUSTOMER_SINGLE_REQUEST";
export const CUSTOMER_SINGLE_SUCCESS = "CUSTOMER_SINGLE_SUCCESS";
export const CUSTOMER_SINGLE_FAIL = "CUSTOMER_SINGLE_FAIL";
export const CUSTOMER_SINGLE_RESET = "CUSTOMER_SINGLE_RESET";

export const CUSTOMER_UPDATE_REQUEST = "CUSTOMER_UPDATE_REQUEST";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAIL = "CUSTOMER_UPDATE_FAIL";
export const CUSTOMER_UPDATE_RESET = "CUSTOMER_UPDATE_RESET";

export const CUSTOMER_CHANGE_REQUEST = "CUSTOMER_CHANGE_REQUEST";
export const CUSTOMER_CHANGE_SUCCESS = "CUSTOMER_CHANGE_SUCCESS";
export const CUSTOMER_CHANGE_FAIL = "CUSTOMER_CHANGE_FAIL";
export const CUSTOMER_CHANGE_RESET = "CUSTOMER_CHANGE_RESET";

export const CUSTOMER_UPDATE_PROFILE_REQUEST = "CUSTOMER_UPDATE_PROFILE_REQUEST";
export const CUSTOMER_UPDATE_PROFILE_SUCCESS = "CUSTOMER_UPDATE_PROFILE_SUCCESS";
export const CUSTOMER_UPDATE_PROFILE_FAIL = "CUSTOMER_UPDATE_PROFILE_FAIL";
export const CUSTOMER_UPDATE_PROFILE_RESET = "CUSTOMER_UPDATE_PROFILE_RESET";

export const CUSTOMER_DELETE_REQUEST = "CUSTOMER_DELETE_REQUEST";
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS";
export const CUSTOMER_DELETE_FAIL = "CUSTOMER_DELETE_FAIL";
export const CUSTOMER_DELETE_RESET = "CUSTOMER_DELETE_RESET";
