export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";

export const ORDER_SEARCH_LIST_REQUEST = "ORDER_SEARCH_LIST_REQUEST";
export const ORDER_SEARCH_LIST_SUCCESS = "ORDER_SEARCH_LIST_SUCCESS";
export const ORDER_SEARCH_LIST_FAIL = "ORDER_SEARCH_LIST_FAIL";

export const ORDER_SEARCH_D2D_LIST_REQUEST = "ORDER_SEARCH_D2D_LIST_REQUEST";
export const ORDER_SEARCH_D2D_LIST_SUCCESS = "ORDER_SEARCH_D2D_LIST_SUCCESS";
export const ORDER_SEARCH_D2D_LIST_FAIL = "ORDER_SEARCH_D2D_LIST_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_CONFORM_REQUEST = "ORDER_CONFORM_REQUEST";
export const ORDER_CONFORM_SUCCESS = "ORDER_CONFORM_SUCCESS";
export const ORDER_CONFORM_FAIL = "ORDER_CONFORM_FAIL";
export const ORDER_CONFORM_RESET = "ORDER_CONFORM_RESET";

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL";
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET";

export const ORDER_COMPLETED_REQUEST = "ORDER_COMPLETED_REQUEST";
export const ORDER_COMPLETED_SUCCESS = "ORDER_COMPLETED_SUCCESS";
export const ORDER_COMPLETED_FAIL = "ORDER_COMPLETED_FAIL";
export const ORDER_COMPLETED_RESET = "ORDER_COMPLETED_RESET";

//usser
export const ORDER_CANCELED_REQUEST = "ORDER_CANCELED_REQUEST";
export const ORDER_CANCELED_SUCCESS = "ORDER_CANCELED_SUCCESS";
export const ORDER_CANCELED_FAIL = "ORDER_CANCELED_FAIL";
export const ORDER_CANCELED_RESET = "ORDER_CANCELED_RESET";

//usser
export const ORDER_RECEIVED_REQUEST = "ORDER_RECEIVED_REQUEST";
export const ORDER_RECEIVED_SUCCESS = "ORDER_RECEIVED_SUCCESS";
export const ORDER_RECEIVED_FAIL = "ORDER_RECEIVED_FAIL";
export const ORDER_RECEIVED_RESET = "ORDER_RECEIVED_RESET";

